#!/bin/bash
set -euo pipefail

# go to script dir
cd "$(dirname "$(readlink -f "$0")")"

# create data dir
if ! [[ -d "$(pwd)/data" ]]; then
	mkdir "$(pwd)/data"
fi

# get widgets results
cd widgets
col=$(grep 'col=' ../config | sed 's/.*col=//')
# execute widgets in columns
f=()
for i in $(seq 1 "${col}"); do
	f[i]=""
	for w in $(awk '!/^#/ {print $'$i'}' ../config); do
		if [ -e "${w}" ]; then
			f[i]+=""
			f[i]+="$(./"${w}")\n\n"
		fi
	done
done

# print
motd=''
for c in "${f[@]}"; do
	[[ -z ${motd} ]] && motd="${c}" || motd=$(paste <(echo -e "${motd}") <(echo -e "${c}") -d'@')
done
motd=${motd::-3} # remove trailing newlines
echo -e "${motd}" | sed 's,@, @ ,' | column -ts '@'
