#!/bin/bash
set -euo pipefail

# Print network information.
# All local interafces and IPs, public IP, hostname.
# Run it to see what it looks like.

toolPath=$(realpath "$(dirname "$0")/../tools")
source "${toolPath}/colors.sh"
dataPath=$(realpath "$(dirname "$0")/../data")

# public IP
stamp="${dataPath}/network-public-ip"
if [ -z "$(find "$stamp" -newermt 'now -1 day' 2>/dev/null)" ]; then
    # cache too old
    publicIp=$(dig +short -4 myip.opendns.com @resolver1.opendns.com)
    echo "${publicIp}" >"${stamp}"
else
    # cache fresh
    publicIp=$(cat "$stamp")
fi

ips=$(ip -oneline addr show | awk '{print $1" " $2" "$4}' | cut -c 4- | grep -Ev " fe80:|^lo ")
publicIp="public $publicIp"

message="$ips\n$publicIp"

echo 'network:'
echo -e "$message" | column -ts' ' | sed 's,^,  ,'
echo "  hostname: $(uname -n)"
