#!/bin/bash
set -euo pipefail

# Print status of services.
# Run it to see what it looks like.

# config
columns=2 # fills row-major
services=('rsyslog' 'cron' 'logrotate.timer' 'sshd' 'networking')
servicesDisplayNames=('syslog' 'cron' 'logrotate' 'sshd' 'network')

toolPath=$(realpath "$(dirname "$0")/../tools")
source "${toolPath}/colors.sh"

out=''
for i in "${!services[@]}"; do
	serviceStatus=$(systemctl is-active "${services[i]}") || true
	serviceStatus=$(c_match "${serviceStatus}" 'active')
	out+="${servicesDisplayNames[$i]}|${serviceStatus}|"
	((((i + 1) % columns) == 0)) && out+='\n'
done
out+='\n'

echo 'services:'
echo -e "${out}" | column -ts '|' | sed -e 's/^/  /'
